apiVersion: v2
name: basketball-sub
description: A Helm chart for Basketball Substitution Manager
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - basketball
  - react
  - substitution
maintainers:
  - name: Team
home: https://github.com/nctiggy/BBall-sub
